# Generated by Django 4.0.1 on 2022-01-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebView', '0002_event_image_alter_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGRICULTURE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descption', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='media/')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CONSTRUCTION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descption', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='media/')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CONSULTANT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descption', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='media/')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EDUCATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descption', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='media/')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FARM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descption', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='media/')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MICROCREDIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descption', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='media/')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PLOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descption', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='media/')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UNDERGRADUATE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descption', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='media/')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
