# Generated by Django 4.0.1 on 2022-02-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebView', '0004_broker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='time',
        ),
    ]
