# Generated by Django 4.0.1 on 2022-02-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebView', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
